### PR TITLE
Fixed Duplicate flags  , closes #382

### LINKED ISSUE #382: Duplicated flags
I registered a new account and added some flags. Flags are displayed duplicated in the profile. That is wrong and should not happen.

Bildschirmfoto 2024-05-02 um 15 32 55

### PR DESCRIPTION
**Pull request by MICHAELMUNAVU83**
- In this PR I fixed the error that showed duplicate flags , we now have it as such
Screenshot 2024-05-03 at 09 26 36

### CODE REVIEW

File: lib/animina_web/live/chat_live.ex [hunk 1]
```diff
@@ -161,6 +161,7 @@ defmodule AniminaWeb.ChatLive do
       |> Enum.filter(fn x ->
         find_user_flag_for_a_flag(user.flags_join_assoc, x).color == color
       end)
+      |> Enum.uniq()
```
Comment (wintermeyer) [inline lib/animina_web/live/chat_live.ex]: Why do we have to run a `uniq/1` here at all? Shouldn't it be unique right away? Where is the duplication coming from?

**Review by wintermeyer — CHANGES_REQUESTED** [review]

File: lib/animina_web/live/chat_live.ex (hunk 1 above)
Comment (wintermeyer) [reply lib/animina_web/live/chat_live.ex]: What I mean: Do we have two entries in the database for the same flag (same color)? Because that should not be happening.

Comment (MICHAELMUNAVU83) [reply lib/animina_web/live/chat_live.ex]: Let me have a closer look at our query and get back

Comment (MICHAELMUNAVU83) [reply lib/animina_web/live/chat_live.ex]: I have found the bug 
```
defp find_user_flag_for_a_flag(user_flags, flag) do
    Enum.find(user_flags, fn x -> x.flag_id == flag.id end)
  end
```

this function returns duplicates and in this case a user may have the same white and green flags

Comment (MICHAELMUNAVU83) [reply lib/animina_web/live/chat_live.ex]: @wintermeyer  , we may run into problems with the current implimentation where we preload individual flags , here is the related issue #353 , I suggest we go back to fetching the flags through the "user_flags" as we can filter explicity using the color.

For example , since someone can have the same white and red flag or white and green flag , when we fetch the user_flags associated with a flag_id , we will get 2 or 3 records .
IMO having the  using the previous one where we get a flag by `flag.flag.id` etc would work best

Comment (wintermeyer) [reply lib/animina_web/live/chat_live.ex]: OK, go back if needed. But please avoid code which read like `flag.flag.name` like we had in the past. That is not easy to understand. 

I am pretty sure we can find a clever way to add the `flag.name` information to the `user_flag` resource. So that we could do something like ´current_user.user_flags` and not `current_user.user_flags[0].flag`.

Fire at will.

Comment (wintermeyer) [reply lib/animina_web/live/chat_live.ex]: Should I merge this PR or not?

Comment (MICHAELMUNAVU83) [reply lib/animina_web/live/chat_live.ex]: No , Let me get at fixing it , in a couple of hours I will have found the best solution

Comment (MICHAELMUNAVU83) [reply lib/animina_web/live/chat_live.ex]: @wintermeyer  , for readability , would changing the access point name be better  , so we have  `user.traits.flag.name`

**Review by wintermeyer — APPROVED** [review]
