### PR TITLE
Fix state checker for images to ensure they can be seen , closes #1143

### LINKED ISSUE #1143: Images are not Visible If they Are approved
Images are not visible that are approved , this is because we have a checker that is looking for the state :appoved but ash returns it as "approved" , thus , we do not see the image

Screenshot 2024-11-13 at 06 02 33

### PR DESCRIPTION
**Pull request by MICHAELMUNAVU83**
Good news , we can now see images  , I also added test cases for this
Screenshot 2024-11-13 at 05 52 47
Screenshot 2024-11-13 at 05 51 32
Screenshot 2024-11-13 at 05 51 50
Screenshot 2024-11-13 at 05 52 18

### CODE REVIEW

File: lib/animina_web/components/bookmark/bookmark_component.ex [hunk 1]
```diff
@@ -55,6 +55,17 @@ defmodule AniminaWeb.BookmarkComponent do
     end
   end
 
+  # we display the state as an atom in the photo struct, but we need to make sure it is an atom
```
Comment (wintermeyer) [inline lib/animina_web/components/bookmark/bookmark_component.ex:58]: When I read this I ask myself WHY do we need to make sure if we already save it as an atom? Please add that this is probably a bug in Ash. Bonus points for adding a link to the bug report you created for Ash.

File: lib/animina_web/components/bookmark/bookmark_component.ex [hunk 2]
```diff
@@ -65,6 +76,13 @@ defmodule AniminaWeb.BookmarkComponent do
         language={@language}
         reason={@reason}
         current_user={@current_user}
+        state={
+          if @current_user.profile_photo && is_atom(@current_user.profile_photo.state) do
```
Comment (wintermeyer) [inline lib/animina_web/components/bookmark/bookmark_component.ex:80]: Don't we have a logic problem here? What if there is no photo? Than make_sure_photo_state_is_atom is called. Is that correct?

File: lib/animina_web/components/chat/chat_components.ex [hunk 3]
```diff
@@ -115,7 +115,16 @@ defmodule AniminaWeb.ChatComponents do
             </div>
           </div>
         </div>
-        <.sender_user_image user={@sender} />
+        <.sender_user_image
+          state={
+            if @sender.profile_photo && is_atom(@sender.profile_photo.state) do
```
Comment (wintermeyer) [inline lib/animina_web/components/chat/chat_components.ex:120]: Same potential logic problem if there is no `profile_photo`.

File: lib/animina_web/components/bookmark/bookmark_component.ex [hunk 4]
```diff
@@ -55,6 +55,17 @@ defmodule AniminaWeb.BookmarkComponent do
...
   end
 
+  # we display the state as an atom in the photo struct, but we need to make sure it is an atom
+  # as we are using it for pattern matching
+
+  defp make_sure_photo_state_is_atom(nil) do
+    ""
+  end
+
+  defp make_sure_photo_state_is_atom(photo) do
```
Comment (wintermeyer) [inline lib/animina_web/components/bookmark/bookmark_component.ex:65]: What happens if this already is an atom? Or are we sure that this can not happen?

File: lib/animina_web/components/chat/chat_components.ex [hunk 5]
```diff
@@ -125,7 +134,17 @@ defmodule AniminaWeb.ChatComponents do
     ~H"""
     <%= if @sender.id != @message.sender_id do %>
       <div class="flex justify-start gap-4  item-start text-black">
-        <.receiver_user_image user={@receiver} current_user={@sender} />
+        <.receiver_user_image
+          state={
+            if @receiver.profile_photo && is_atom(@receiver.profile_photo.state) do
```
Comment (wintermeyer) [inline lib/animina_web/components/chat/chat_components.ex:139]: This cries out loud to become some sort of helper function. DRY!

As fare as I understand it we are dealing with a potential Ash bug here. There will come a time when that bug is fixed. It is so much easier than to just fix one helper function than to walk through all the other code.

File: lib/animina_web/components/chat/chat_components.ex [hunk 6]
```diff
@@ -321,4 +340,12 @@ defmodule AniminaWeb.ChatComponents do
   def format_time(time) do
     NaiveDateTime.from_erl!({{2000, 1, 1}, Time.to_erl(time)}) |> Timex.format!("{h12}:{0m} {am}")
   end
+
+  defp make_sure_photo_state_is_atom(nil) do
```
Comment (wintermeyer) [inline lib/animina_web/components/chat/chat_components.ex:344]: DRY

**Review by wintermeyer — APPROVED** [review]
@MICHAELMUNAVU83 I approve this PR to fix the problem in production. But please do create a new issue to DRY this code and do that.

File: lib/animina_web/components/bookmark/bookmark_component.ex (hunk 4 above)
Comment (MICHAELMUNAVU83) [reply lib/animina_web/components/bookmark/bookmark_component.ex:65]: We have this is_atom(@sender.profile_photo.state)

File: lib/animina_web/components/chat/chat_components.ex (hunk 5 above)
Comment (MICHAELMUNAVU83) [reply lib/animina_web/components/chat/chat_components.ex:139]: Very True , I will have a seperate issue for this

File: lib/animina_web/components/bookmark/bookmark_component.ex (hunk 4 above)
Comment (wintermeyer) [reply lib/animina_web/components/bookmark/bookmark_component.ex:65]: > We have this is_atom(@sender.profile_photo.state)

So we check it in two different places? Wouldn't it be better to do this in one place/area?

Comment (MICHAELMUNAVU83) [reply lib/animina_web/components/bookmark/bookmark_component.ex:65]: It would , I will refactor this code , already an issue for it
