### PR TITLE
form input for story update , closes #1077

### LINKED ISSUE #1077: Text box resized to default height after every Enter
Description:
Text box is resized to default height after every Enter key stroke.

Steps to reproduce: 
- add a new story
- increase height of text box for content
- click in the text box and press Enter
  (or write some text and press Enter)

Expected behavior:
Height should be unchanged.

Browser: Firefox 130, Linux

### PR DESCRIPTION
**Pull request by Kimutai01**
-I have removed the ablility to resize the text box
-I have enabled a user to see all the text content that they have written.

https://github.com/user-attachments/assets/ead31541-fc6b-465a-8b11-1f787234baf5

### CODE REVIEW

File: assets/js/app.js [hunk 1]
```diff
@@ -32,6 +32,23 @@ let csrfToken = document
 
 let Hooks = {};
 
+Hooks.AutoResizeTextarea = {
```
Comment (wintermeyer) [inline assets/js/app.js]: Please remove this code. 

Sorry, for not having made that clearer: 
- We make the text field 3 rows higher in the desktop. 
- We leave the mobile version as it is. 
- We deactivate the possibility to resize the text field. 
- We do not add any JavaScript magic to auto enlarge it.

**Review by wintermeyer — CHANGES_REQUESTED** [review]

**Comment by Kimutai01** [comment]
https://github.com/user-attachments/assets/3174cf59-f945-4b0e-8a83-371f98312240

-I have deactivated the ability to resize the text field.

**Review by wintermeyer — APPROVED** [review]
