### PR TITLE
fix upload image form validation, closes #74

### LINKED ISSUE #74: ImageCropper doesn't work
After days of work on this feature it still doesn't work on my macOS 14.1.2 (Safari and Chrome).

ScreenFlow

I am getting frustrated by this.

@briankariuki Please fix it today or rip it out of the code. We do not need an ImageCropper. It is a nice to have feature but this takes way too much energy and time.

### PR DESCRIPTION
**Pull request by briankariuki**
I've tested this on safari and chrome. It now works

### CODE REVIEW

File: config/dev.exs [hunk 1]
```diff
@@ -57,7 +57,7 @@ config :animina, AniminaWeb.Endpoint,
 config :animina, AniminaWeb.Endpoint,
   live_reload: [
     patterns: [
-      ~r"priv/static/.*(js|css|png|jpeg|jpg|gif|svg)$",
+      ~r"priv/static/(?!uploads/).*(js|css|png|jpeg|jpg|gif|svg)$",
```
Comment (wintermeyer) [inline config/dev.exs:60]: In my setup I get an error here because I don't have a `uploads` directory. Please check it into the repo with a `.gitkeep` file in it.

**Review by wintermeyer — CHANGES_REQUESTED** [review]
Please tell me at what point I should see the image cropping tool because I do not see it when I upload a non square image.

**Comment by wintermeyer** [comment]
> Please tell me at what point I should see the image cropping tool because I do not see it when I upload a non square image.

Square. I meant a non square image. I fixed the comment but wanted to be sure. When I upload a non square image I do not see any tool to crop it. Please tell me how ImageCropper should work. I want to make sure that I am looking for the right thing.

**Comment by briankariuki** [comment]
> > Please tell me at what point I should see the image cropping tool because I do not see it when I upload a non square image.
> 
> Square. I meant a non square image. I fixed the comment but wanted to be sure. When I upload a non square image I do not see any tool to crop it. Please tell me how ImageCropper should work. I want to make sure that I am looking for the right thing.

I've drilled down the issue to how the file is selected. If one clicks the drop target and chooses a file from the files dialog the cropping will work. This is because the `onchange` event on the `live_file_input` will be triggered. The cropping logic depends on this event. However, on `drag and drop` this event does not get fired on the `live_file_input` when the file is dropped successfully.

I'm working on seeing if I can work around this. For now you can test the cropping by picking the file from the file picker. You can then right click the image shown and open in a new tab to see the cropped version. below is a cropped version of the image you shared with me.

image

How the cropped version looks:

image

**Comment by wintermeyer** [comment]
> For now you can test the cropping by picking the file from the file picker.

I can't. This is me using the file picker:

file-picker

**Comment by briankariuki** [comment]
> > For now you can test the cropping by picking the file from the file picker.
> 
> I can't. This is me using the file picker:
> 
> file-picker [ file-picker ](https://private-user-images.githubusercontent.com/69770/308143302-9779b272-846e-415a-8eae-4e0f2c158315.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwMzQyMjMsIm5iZiI6MTcwOTAzMzkyMywicGF0aCI6Ii82OTc3MC8zMDgxNDMzMDItOTc3OWIyNzItODQ2ZS00MTVhLThlYWUtNGUwZjJjMTU4MzE1LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI3VDExMzg0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ1YTk4M2I2ZjE4ZmU4MzJlMjg4ZDRhNzRmNGM3YWE4ODZmNWUzZTkzNzFkOGFlMDE0OWI1MWU2YzVlMGFjZjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9_JN-IIuFbfzZKDDGiX3awbjqFZQf0ANkSsHtK21zUg) [ ](https://private-user-images.githubusercontent.com/69770/308143302-9779b272-846e-415a-8eae-4e0f2c158315.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwMzQyMjMsIm5iZiI6MTcwOTAzMzkyMywicGF0aCI6Ii82OTc3MC8zMDgxNDMzMDItOTc3OWIyNzItODQ2ZS00MTVhLThlYWUtNGUwZjJjMTU4MzE1LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI3VDExMzg0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ1YTk4M2I2ZjE4ZmU4MzJlMjg4ZDRhNzRmNGM3YWE4ODZmNWUzZTkzNzFkOGFlMDE0OWI1MWU2YzVlMGFjZjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9_JN-IIuFbfzZKDDGiX3awbjqFZQf0ANkSsHtK21zUg)

For now, I just reset the form on succesful upload. The file is stored in the `priv/static/uploads` folder. Once the tags feature is complete we can redirect the user to that page.
